server:
  port: 8081
  servlet:
    context-path: /api

spring:
  data:
    mongodb:
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      database: patra_db
      uri: mongodb://localhost:27017

cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false