server:
  port: 8081
  servlet:
    context-path: /api


spring:
  data:
    mongodb:
      authentication-database: admin
      field-naming-strategy: org.springframework.data.mapping.model.SnakeCaseFieldNamingStrategy
      database: patra_db
      uri: mongodb://localhost:27017
cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: AKIAQ3K3MF3UPURFYCVB
      secret-key: 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
      instance-profile: false
    stack:
      auto: false